### ISSUE TITLE
BMM Export Crash

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-flows#163]
https://temporal.bcc.media/namespaces/default/workflows/2811194b-7509-4c33-925e-125da91d0226_50/0eb7e366-64b4-45fd-bbaa-2c5bb0512d0f/history

```
  "source": "GoSDK",
  "stackTrace": "coroutine root [panic]:\ngithub.com/bcc-code/bcc-media-flows/workflows/export.prepareBMMData(0x1187100?, 0xc000d627e0?)\n\t/src/workflows/export/vx_export_bmm.go:270 +0x450\ngithub.com/bcc-code/bcc-media-flows/workflows/export.VXExportToBMM({_, _}, {{0xc000bd0ba0, 0x24}, {{0xc000d67950, 0x9}, 0x0, 0x0, {0x0, 0x0}, ...}, ...})\n\t/src/workflows/export/vx_export_bmm.go:138 +0xdbd\nreflect.Value.call({0x11f8b40?, 0x14b15f0?, 0x7f289f27d188?}, {0x1403c0c, 0x4}, {0xc000fa5d40, 0x2, 0x0?})\n\t/usr/local/go/src/reflect/value.go:596 +0xce7\nreflect.Value.Call({0x11f8b40?, 0x14b15f0?, 0xc000b89d30?}, {0xc000fa5d40?, 0xc000cc8b20?, 0x20?})\n\t/usr/local/go/src/reflect/value.go:380 +0xb9\ngo.temporal.io/sdk/internal.executeFunction({0x11f8b40, 0x14b15f0}, {0xc000cc8b20, 0x2, 0x11d3ea0?})\n\t/go/pkg/mod/go.temporal.io/sdk@v1.24.0/internal/internal_worker.go:1797 +0x25a\ngo.temporal.io/sdk/internal.(*workflowEnvironmentInterceptor).ExecuteWorkflow(0xc00101f040, {0x15fbbb0?, 0xc001184ea0}, 0xc000a7d308)\n\t/go/pkg/mod/go.temporal.io/sdk@v1.24.0/internal/workflow.go:528 +0x165\ngo.temporal.io/sdk/internal.(*workflowExecutor).Execute(0xc000c39180, {0x15fbbb0, 0xc001184ea0}, 0x25?)\n\t/go/pkg/mod/go.temporal.io/sdk@v1.24.0/internal/internal_worker.go:805 +0x286\ngo.temporal.io/sdk/internal.(*syncWorkflowDefinition).Execute.func1({0x15fa818, 0xc000fa5ad0})\n\t/go/pkg/mod/go.temporal.io/sdk@v1.24.0/internal/internal_workflow.go:512 +0xc2",
```

**Comment by KillerX** [comment]
ChatGPT "reformat" of the stack trace:

Source: GoSDK
Error Location: github.com/bcc-code/bcc-media-flows/workflows/export

Error Summary:
- Panic occurred in prepareBMMData function.
- Location: /src/workflows/export/vx_export_bmm.go, Line: 270
- Called by VXExportToBMM function at /src/workflows/export/vx_export_bmm.go, Line: 138
- Further invoked functions include reflect.Value.call and reflect.Value.Call, leading to the execution of the workflow.

Stack Trace Details:
1. prepareBMMData failed with a panic.
2. VXExportToBMM encountered an error, attempted to handle data export.
3. Reflect API used to call functions dynamically encountered errors.
4. Internal workflow execution processes were triggered, leading to the error.

**Comment by fredrikved** [comment]
![image](https://github.com/bcc-code/bcc-media-flows/assets/75886490/895784eb-0a06-4b35-ba1b-b3c94a806d4f)
Output analysis is nil here.
