### ISSUE TITLE
Dubbing export flow

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#213]
Export dubbing files of VB to Oslofjord dubbing reaper machine
 
1. Relate audio to VB
2. Update asset relation
3. Add all the languages needed on "language export"
4. Add "Reaper dubbing" as destinations export
5. Click export asset
6. Audio tracks will end up at \\10.12.10.10 Delivvery\FraMB\Reaper-wav with trackNumber_languageCode at the end of the name e.g. BIST_S01_E07_MAS_NORmov_1_nor

**Comment by mulundapm** [comment]
Have exported VX-483690 and the norwegian audio file (BIST_S01_E07_MAS_NOR_NOR_1_nor) sounds horrible. Exported a different asset to test, it didnt have the same issue. @KillerX

**Comment by KillerX** [comment]
The underlying audio file is broken. Should be handled as a separate issue.
