### ISSUE TITLE
"Approve chapter title" for types that are not tale || vitnesbyrd || appelle || sang || musikkvideo || singalong

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#275]
Current logic:

If type is ( tale || vitnesbyrd || appelle || sang || musikkvideo || singalong) , export chapter with its chapter title. Else, export chapter with chapter type as title

Wanted:

As an admin, I want to manually go through chapter titles for types that are not tale, vitnesbyrd... and approve the title before displaying the chapter title in vod. 

Export title if approved

**Comment by andreasgangso** [comment]
@mulundapm let me know once you've added something for this to MB

**Comment by mulundapm** [comment]
![Image](https://github.com/bcc-code/bcc-media-flows/assets/88234679/7e6708a6-b4ae-4e2f-9be3-7b59e02592e6)
