### ISSUE TITLE
Option to export asset with chapters

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#276]
Previously, if the "With chapters" is checked in the export form, all chapters timemetadata within the assets are being exported together with the asset. Now the timemetadata is not being exported regardless if "with chapters" is checked. 

It is possible to export timed metadata separately, however, admin will have to wait until the asset is available in vod before triggering the export timed metadata. 

Would want to have an option to export asset and timed metadata tgt if the metadata is found

**Comment by andreasgangso** [comment]
This seems to be working fine, actually?
See e.g. the export you did for VX-315802

**Comment by andreasgangso** [comment]
@mulundapm
