### ISSUE TITLE
Transcription tool improvements

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#285]
Test the new neural network from South Africa
https://github.com/bcc-code/bccmedia-song-or-not/pull/1

Whisper has finetuned in Norwegian 
https://huggingface.co/NbAiLab/nb-whisper-large

Check gpt-4o / open source alternatives

Questions to answer
- Is there a better model after 1.5 years (probably not)
- can we use something finetuned for only norwegian
- can we use an LLM to fix the text?

**Comment by KillerX** [comment]
This is now deployed and after fixing the deadlock bug, seems to be working.
