### ISSUE TITLE
Export only transcription to bmm

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#295]
Transcription for meeting is often not ready when audio is being exported to bmm. Need solution to make sure transcription is available without re-exporting audio to bmm

**Comment by KillerX** [comment]
Split into #307

**Comment by KillerX** [comment]
Considering #307 and the fact that of the last 14/15 live ingests had the transcription finished before the audio import was done (and the other one very soon after) i propose the following:

* We do not implement the feature as specified
* We add a notification to telegram for when the transcription is completed

This allows for:

* Re-export with audio + text
   * I have validated that BMM imports the text in this case 
* Wait a few minutes and get the text on the first go

@kkuepper @mulundapm any comments?
