### ISSUE TITLE
BMM Export transcriptions not arriving in BMM

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-flows#307]
Currently transcriptions do not end up in BMM even when they exist in MB when exporting.

Expected: The "transcription" tab in BMM admin should show the transcribed text if the MB item had transcriptions in norwegian

**Comment by KillerX** [comment]
The language coding for text in mb is for some legacy reason a 2 letter code. BMM expected the 3 letter code so the text was ignored. The export flow now translates the language code so it is understood correctly by BMM.
I have tested against integration.

**Comment by mulundapm** [comment]
I have exported VX-489598 to int. MB shows there is transcription for this asset, but the transcription is not being exported

https://int-bmm.brunstad.org/admin/track/113899

**Comment by KillerX** [comment]
The asset above only had SRT transcription and not JSON. It is unclear why and if that is the case elsewhere, it needs to be investigated as a separate bug.

**Comment by KillerX** [comment]
> The asset above only had SRT transcription and not JSON. It is unclear why and if that is the case elsewhere, it needs to be investigated as a separate bug.

I have checked some 40 files from the last months and have not found a single video that JSON transcription missing. If we discover that future new files are missing JSON transcriptions, we should open a bug to investigate that. The workaround is to just hit the "transcribe" button again for any old material that is missing the json format.

**Comment by mulundapm** [comment]
exported bjørn nilsen vx-489975 to bmm but transcription is not shown on bmm

**Comment by kkuepper** [comment]
the transcription wasn't ingested if it was a new track. That's now been fixed.

There still seems to be a bug, which leads to a new track being created instead of adding to the existing one. I don't know how that can happen and I'll need to investigate the logs, when it happens again.
