### ISSUE TITLE
Series_Masters - FC Import Flow

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-flows#31]
- [x] Validate that only one file is being delivered
- [x] Generate filename (current code below)
- [x]  Move file to a appropriate location (/mnt/isilon/Production/masters/currentyear/currentmonth/currentday/flowid)
- [x] Set Metadata
   - Uploaded By
   - Upload JOB ID
   - Language recorded (from XML)
   - [x] Start Audio analysis #39
 - [x] Start QC process #38
 - [x] Generate preview - Start a different flow in parallel
 - [x] Generate transcription - Start a different flow in parallel

**Comment by fredrikved** [comment]
Same filename as Other masters?

I don't have access to the form at the moment, so I can't verify the input parameters.
