### ISSUE TITLE
use transcriptions for VOD subtitles

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-media-flows#314]
Current: When exporting, automatic transcriptions are not exported to VOD.

Change: Fallback to automated transcriptions if available and export those.

Result: When watching a VOD we should be able to see auto translated subtitles

mark subtitles as beeing (auto-generated) (AI)

**Comment by KillerX** [comment]
This is in code-review, tested locally, but not tested what the end result looks like in a player. Needs to be deployed and something exported first!

**Comment by KillerX** [comment]
There seems to be a bug in the export, that appears when this is used. Investigating.

**Comment by KillerX** [comment]
Fixed and tested.
