### ISSUE TITLE
VB Master - FC Import Flow

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-flows#32]
https://www.notion.so/bccmedia/delivery-brunstad-tv-VB-master-be4aec0807aa40cc9cf92dfdb4182113?pvs=4

Current description:

Renaming of files take place, only one file allowed, no locks/blockers on files not passing QC.
Differ from the other Master-variants in metadatafields and renaming rules

- [x] #50

**Comment by fredrikved** [comment]
Blocked due to the upcoming camp. Don't want to disable the old flow for testing in case it is used.
