### ISSUE TITLE
stabilize bmm upload form

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bcc-media-flows#323]

**Comment by KillerX** [comment]
* Moved the subtitle preview import into an independant job so that will not be able to break the system
* Updated timeouts so any deadlocks and such are detected earlier
* Some minor UI qol improvements

**Comment by KillerX** [comment]
@kkuepper I do not have any more ideas that we would need to do here before we open it up more. Any comments?

**Comment by KillerX** [comment]
Also added flags now
