### ISSUE TITLE
transcription missing on the 16. 17. sept frakåre

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#329]
Karsten re-exported the 2 episodes in the major languages (nb, en, de, nl, fr) so that the transcription is available in those.

observed facts
- the import jobs that BMM receives don't link any transcriptions (just the audio files)
- can't see a bug on BMM side
- exporting just the transcription works
- the asset in mediabanken has the transcription

Theory:
The export to BMM is triggered before the transcription is processed / available.

**Comment by KillerX** [comment]
The theory seems correct.

Initially we waited for the preview/sidecar to be imported and that was the longest part of the job anyway. When I removed that wait I did not add the wait for the JSON file that we actually need. 

See #330
