### ISSUE TITLE
Generate audio preview on import for softron

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#343]

**Comment by KillerX** [comment]
Test Here: https://mediabanken.brunstad.tv/item/VX-493926/?index=0&search_id=192634&parentPage=search

Current known issues:

* MU1, MU2 -> Stereo tracks are silent
* The extra tracks are imported as "videos" for some reason

**Comment by KillerX** [comment]
Jana says that it's ok the way it's now (with no picture).

**Comment by KillerX** [comment]
Note that this is currently only implemented on closed files import (i.e. *not* growing files).
