### ISSUE TITLE
Playout export cannot be completed

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#76]
Exporting VX-468696 to playout failed

Definition of done:
Exported and played in playout successfully

**Comment by mulundapm** [comment]
what is the status on this? @fredrikved

**Comment by fredrikved** [comment]
Waiting for response from Brunstad.

**Comment by mulundapm** [comment]
Can set it as blocked then

**Comment by KillerX** [comment]
I think this is resolved.
