### ISSUE TITLE
Flows - Watchfolders

### ISSUE THREAD

**Issue by KillerX** [bcc-code/bcc-media-flows#9]
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25

Note: The video transcoding processes should be validated that they:
- Produce the exact same file format according to ffprobe and mediainfo
- are not significantly slower than Vantage (i.e. a small benchmark should be performed)

**Comment by mulundapm** [comment]
Follow up with Henning regard user cases
