### ISSUE TITLE
Test mac for export

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#90]

**Comment by fredrikved** [comment]
The mac mini for test has no power...

Same file encoded and decoded at 0.5x speed while my mac does it at 8x.

**Comment by fredrikved** [comment]
Did some more testing.

libx264 software encoding of a 10 minute animation video:

**mac mini:**
`ffmpeg -hide_banner -progress pipe:1 -i /private/temp/workflows/d4f18297-314d-4a76-a57a-cfde54407ccc/Hstcamp_2023_HIST_E09_MAS_NOR.mxf -i /private/isilon/system/assets/BTV_LOGO_WATERMARK_BUG_GFX_1080.png -c:v libx264 -profile:v high422 -level:v 1.3 -preset slow -tune film -vsync 1 -g 48 -pix_fmt yuv420p -x264opts no-scenecut -crf 22 -write_tmcd 0 -r 25 -filter_complex "[0:0] scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 [main];[main][1:0] overlay=main_w-overlay_w:0 [main];[main] scale=1920:1080:force_original_aspect_ratio=decrease [out]" -map "[out]" /private/temp/test7.mp4`

- caps at 750% CPU
- bottoms out at 1.9x speed

**transcode01:**
`ffmpeg -hide_banner -progress pipe:1 -i /mnt/temp/workflows/d4f18297-314d-4a76-a57a-cfde54407ccc/Hstcamp_2023_HIST_E09_MAS_NOR.mxf -i /mnt/isilon/system/assets/BTV_LOGO_WATERMARK_BUG_GFX_1080.png -c:v libx264 -profile:v high422 -level:v 1.3 -preset slow -tune film -vsync 1 -g 48 -pix_fmt yuv420p -x264opts no-scenecut -b:v 5M -crf 22 -write_tmcd 0 -r 25 -filter_complex "[0:0] scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2 [main];[main][1:0] overlay=main_w-overlay_w:0 [main];[main] scale=1920:1080:force_original_aspect_ratio=decrease [out]" -map "[out]" -y /mnt/temp/test6.mp4`

- caps at 2400% CPU
- bottoms out at 3.3x speed
