### ISSUE TITLE
Fix reaper usync for åpning and avslutning

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#92]
https://mediabanken.brunstad.tv/item/VX-471374/?index=26&search_id=174547&parentPage=search
https://mediabanken.brunstad.tv/item/VX-471441/?index=48&search_id=174641&parentPage=search

**Comment by mulundapm** [comment]
@KillerX Will have to fix this asap. Maybe Janna can do this to off some load?

**Comment by KillerX** [comment]
One is exported already and 2nd is only fixed but not exported to VOD yet
